package server.web.casa.app.property.domain.model

import server.web.casa.app.address.domain.model.*
import server.web.casa.app.user.domain.model.UserDto
import java.time.LocalDate

data class Property(
    val propertyId: Long = 0,
    var title: String,
    var description: String? = "",
    var price: Double,
    var surface: Double? = null,
    var rooms: Int? = 0,
    val bedrooms: Int? = 0,
    var electric: Int? = 1,
    var water: Int? = 1,
    var kitchen: Int? = 0,
    val livingRoom: Int? = 0,
    var guarantee: String = "",
    var bathroom: Int? = 0,
    var floor: Int? = 0,
    var address: String,
    var city: City?,
    var quartier: Quartier?,
    var postalCode: String? = "",
    var commune: Commune?,
    var communeValue: String? = "",
    var quartierValue: String? = "",
    var cityValue: String? = "",
    var countryValue: String? = "",
//    val quartier : String,
    var sold: Boolean,
    var transactionType: String,
    var propertyType: PropertyType,
    val user: UserDto?,
    var latitude: Double? = null,
    var longitude: Double? = null,
    val isAvailable: Boolean = true,
    val features: List<Feature> = emptyList(),
    val favorites: List<PropertyFavorite?> = emptyList(),
    val propertyImage: List<PropertyImage> = emptyList(),
    val propertyImageRoom: List<PropertyImageRoom> = emptyList(),
    val propertyImageLivingRoom: List<PropertyImageLivingRoom> = emptyList(),
    val propertyImageKitchen: List<PropertyImageKitchen> = emptyList(),
    val createdAt: LocalDate = LocalDate.now(),
    var updatedAt: LocalDate = LocalDate.now(),
)
