package server.web.casa.app.property.infrastructure.persistence.mapper

import server.web.casa.app.address.infrastructure.persistence.mapper.*
import server.web.casa.app.property.domain.model.Property
import server.web.casa.app.property.infrastructure.persistence.entity.PropertyEntity
import server.web.casa.app.user.infrastructure.persistence.mapper.*

fun PropertyEntity.toDomain()  = Property(
    propertyId = this.propertyId,
    title = this.title,
    description = this.description,
    price = this.price,
    surface = this.surface,
    rooms = this.rooms,
    guarantee = this.guarantee,
    bedrooms = this.bedrooms,
    kitchen = this.kitchen,
    livingRoom = this.livingRoom,
    bathroom = this.bathroom,
    water = this.water,
    floor = this.floor,
    address = this.address,
    city = this.city?.toDomain() ,
    postalCode = this.postalCode,
    communeValue = this.communeValue,
    quartierValue = this.quartierValue,
    cityValue = this.cityValue,
    countryValue = this.countryValue,
    commune = this.commune?.toDomain(),
    quartier = this.quartier?.toDomain(),
    sold = this.sold,
    electric = this.electric,
    transactionType = this.transactionType,
    propertyType = this.propertyType.toDomain(),
    user = this.user?.toDomain(),
    latitude = this.latitude,
    longitude = this.longitude,
    isAvailable = this.isAvailable,
    features =  this.features.stream().map { it.toDomain() }.toList(),
    propertyImage = this.propertyImage.map { it.toDomain()  }.toList()  ,
    propertyImageRoom = this.propertyImageRoom.stream().map { it.toDomain() }.toList(),
    propertyImageLivingRoom = this.propertyImageLivingRoom.stream().map { it.toDomain() }.toList(),
    propertyImageKitchen = this.propertyImageKitchen.stream().map { it.toDomain() }.toList(),
    createdAt = this.createdAt,
    updatedAt = this.updatedAt
)

fun Property.toEntity() = PropertyEntity(
    propertyId = this.propertyId,
    title = this.title,
    electric = this.electric,
    water = this.water,
    guarantee = this.guarantee,
    description = this.description,
    price = this.price,
    surface = this.surface,
    rooms = this.rooms,
    bedrooms = this.bedrooms,
    kitchen = this.kitchen,
    livingRoom = this.livingRoom,
    bathroom = this.bathroom,
    floor = this.floor,
    address = this.address,
    communeValue = this.communeValue,
    quartierValue = this.quartierValue,
    cityValue = this.cityValue,
    countryValue = this.countryValue,
    city = this.city?.toEntity() ,
    postalCode = this.postalCode,
    commune = this.commune?.toEntity(),
    quartier = this.quartier?.toEntity(),
    sold = this.sold,
    transactionType = this.transactionType,
    propertyType = this.propertyType.toEntity(),
    user = this.user?.toEntityToDto(),
    latitude = this.latitude,
    longitude = this.longitude,
    isAvailable = this.isAvailable,
    features = this.features.stream().map { it.toEntity() }.toList(),
    createdAt = this.createdAt,
    updatedAt = this.updatedAt
)
