package server.web.casa.app.property.infrastructure.persistence.mapper

import server.web.casa.app.property.domain.model.Property
import server.web.casa.app.property.infrastructure.persistence.entity.PropertyEntity

fun PropertyEntity.toDomain()  = Property(
    propertyId = this.id,
    title = this.title,
    description = this.description,
    price = this.price,
    surface = this.surface,
    rooms = this.rooms,
    guarantee = this.guarantee,
    bedrooms = this.bedrooms,
    kitchen = this.kitchen,
    livingRoom = this.livingRoom,
    bathroom = this.bathroom,
    water = this.water,
    floor = this.floor,
    address = this.address,
    city = this.cityId,
    postalCode = this.postalCode,
    communeValue = this.communeValue,
    quartierValue = this.quartierValue,
    cityValue = this.cityValue,
    countryValue = this.countryValue,
    commune = this.communeId,
    quartier = this.quartierId,
    sold = this.sold,
    electric = this.electric,
    transactionType = this.transactionType,
    user = this.user,
    latitude = this.latitude,
    longitude = this.longitude,
    isAvailable = this.isAvailable,
    propertyTypeId = this.propertyTypeId,
    createdAt = this.createdAt,
    updatedAt = this.updatedAt,
)

fun Property.toEntity() = PropertyEntity(
    id = this.propertyId,
    title = this.title,
    electric = this.electric,
    water = this.water,
    guarantee = this.guarantee,
    description = this.description,
    price = this.price,
    surface = this.surface,
    rooms = this.rooms,
    bedrooms = this.bedrooms,
    kitchen = this.kitchen,
    livingRoom = this.livingRoom,
    bathroom = this.bathroom,
    floor = this.floor,
    address = this.address,
    communeValue = this.communeValue,
    quartierValue = this.quartierValue,
    cityValue = this.cityValue,
    countryValue = this.countryValue,
    cityId = this.city ,
    postalCode = this.postalCode,
    communeId = this.commune,
    quartierId = this.quartier,
    sold = this.sold,
    transactionType = this.transactionType,
    propertyTypeId = this.propertyTypeId,
    user = this.user,
    latitude = this.latitude,
    longitude = this.longitude,
    isAvailable = this.isAvailable,
    createdAt = this.createdAt,
    updatedAt = this.updatedAt
)
